services:
  - type: web
    name: boutique-backend
    runtime: python3
    pythonVersion: 3.11.4
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt"
    startCommand: "cd backend/boutique_store && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: boutique_store.settings
      - key: SECRET_KEY
        value: NMgAse9tqdq0NI2bTkni3f3U_JZFqICQ0QnZhjPWz9g04Ato64ett4tkXyEHmsB2MPI
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3